cargo-features = ["edition2024"]

[package]
name = "ratio-fun"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.2.0"
borsh = { version = "1.5", features = ["derive"] }
thiserror = "1"
